/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jogomemoria.control.JogoMemoriaCtrl;
import jogomemoria.model.PecaTabuleiro;

/**
 *
 * @author mathe
 */
public class JogoMemoriaPrincipal2 extends javax.swing.JFrame {

    private JPanelFacil pf;
    private JPanelIntermediario pi;
    private JPanelDificil pd;
    private Tabuleiro jpt = new Tabuleiro();
    private JogoMemoriaCtrl controle;

    /**
     * Creates new form JogoMemoriaPrincipal2
     */
    public JogoMemoriaPrincipal2() {
        initComponents();
        controle = new JogoMemoriaCtrl();
        pf = new JPanelFacil(controle);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sppPrincipal = new javax.swing.JSplitPane();
        pnlPrincipal1 = new javax.swing.JPanel();
        lblTempo = new javax.swing.JLabel();
        spnTempo = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        cmbNivel = new javax.swing.JComboBox<>();
        btnIniciar = new javax.swing.JButton();
        btnIniciar2 = new javax.swing.JButton();
        pnlTituloJogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sppPrincipal.setDividerLocation(60);
        sppPrincipal.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        lblTempo.setText("Tempo Limite:");

        jLabel2.setText("Nivel:");

        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iniciante", "Intermediário", "Difícil" }));
        cmbNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNivelActionPerformed(evt);
            }
        });

        btnIniciar.setText("Cancelar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnIniciar2.setText("Iniciar");
        btnIniciar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipal1Layout = new javax.swing.GroupLayout(pnlPrincipal1);
        pnlPrincipal1.setLayout(pnlPrincipal1Layout);
        pnlPrincipal1Layout.setHorizontalGroup(
            pnlPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipal1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spnTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(btnIniciar2)
                .addGap(18, 18, 18)
                .addComponent(btnIniciar)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlPrincipal1Layout.setVerticalGroup(
            pnlPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipal1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTempo)
                    .addComponent(spnTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciar)
                        .addComponent(btnIniciar2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sppPrincipal.setLeftComponent(pnlPrincipal1);

        pnlTituloJogo.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jmPrincipal2.png"))); // NOI18N
        pnlTituloJogo.add(jLabel1, java.awt.BorderLayout.CENTER);

        sppPrincipal.setBottomComponent(pnlTituloJogo);

        getContentPane().add(sppPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbNivelActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        controle.setJogoIniciado(false);
        mostrarPainel(pnlTituloJogo);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnIniciar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar2ActionPerformed
        // TODO add your handling code here:
        int nivelSelec = 0;
        String nivel = (String) cmbNivel.getSelectedItem();

        if (nivel.equals("Iniciante")) {
            nivelSelec = controle.FACIL;
        }
        if (((String) cmbNivel.getSelectedItem()).equals("Intermediario")) {
            nivelSelec = controle.INTERMEDIARIO;
        }
        if (nivel.equals("Dificil")) {
            nivelSelec = controle.DIFICIL;
        }
        int tempoL = (((Integer) spnTempo.getValue()).intValue());

        sppPrincipal.setRightComponent(jpt);
        this.repaint();
        controle.iniciarPartida(nivelSelec, tempoL);
        mostrarTabuleiro(true);
        int resp = JOptionPane.showConfirmDialog(this, "O Jogo pode ser iniciado ?", "Confirme inicio", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            mostrarTabuleiro(false);
        }

    }//GEN-LAST:event_btnIniciar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoMemoriaPrincipal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnIniciar2;
    private javax.swing.JComboBox<String> cmbNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JPanel pnlPrincipal1;
    private javax.swing.JPanel pnlTituloJogo;
    private javax.swing.JSpinner spnTempo;
    private javax.swing.JSplitPane sppPrincipal;
    // End of variables declaration//GEN-END:variables

    private void mostrarPainel(JPanel pnl) {
        sppPrincipal.setRightComponent(pnl);
    }

    public void mostrarTabuleiro(boolean inicioJogo) {
        PecaTabuleiro pctb[][] = controle.getTabuleiro();
        int idImg;

        if (controle.getNivelAtual() == controle.FACIL) {
            jpt.getSPPTabuleiro().setRightComponent(pf);
            mostrarPainel(jpt);
            this.setSize(800, 600);
        }

        if (controle.getNivelAtual() == controle.INTERMEDIARIO) {
            jpt.getSPPTabuleiro().setRightComponent(pi);
            mostrarPainel(jpt);
            this.setSize(800, 600);
        }
        if (controle.getNivelAtual() == controle.DIFICIL) {
            jpt.getSPPTabuleiro().setRightComponent(pd);
            mostrarPainel(jpt);
            this.setSize(800, 600);

        }
    }
}
