/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

import javax.swing.JSplitPane;

/**
 *
 * @author mathe
 */
public class Tabuleiro extends javax.swing.JPanel {

    /**
     * @return the sppTabuleiro
     */
    public javax.swing.JSplitPane getSppTabuleiro() {
        return sppTabuleiro;
    }

    /**
     * Creates new form Infos
     */
    public Tabuleiro() {
        initComponents();
    }

    public JSplitPane getSPPTabuleiro() {
        return getSppTabuleiro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sppTabuleiro = new javax.swing.JSplitPane();
        jPanelFacil1 = new jogomemoria.gui.JPanelFacil();
        info1 = new jogomemoria.gui.Info();
        jPanel1 = new javax.swing.JPanel();
        sppTabuleiro1 = new javax.swing.JSplitPane();
        jPanelFacil2 = new jogomemoria.gui.JPanelFacil();
        info2 = new jogomemoria.gui.Info();

        setLayout(new java.awt.BorderLayout());

        sppTabuleiro.setLeftComponent(jPanelFacil1);
        sppTabuleiro.setRightComponent(info1);

        add(sppTabuleiro, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        sppTabuleiro1.setLeftComponent(jPanelFacil2);
        sppTabuleiro1.setRightComponent(info2);

        jPanel1.add(sppTabuleiro1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jogomemoria.gui.Info info1;
    private jogomemoria.gui.Info info2;
    private javax.swing.JPanel jPanel1;
    private jogomemoria.gui.JPanelFacil jPanelFacil1;
    private jogomemoria.gui.JPanelFacil jPanelFacil2;
    private javax.swing.JSplitPane sppTabuleiro;
    private javax.swing.JSplitPane sppTabuleiro1;
    // End of variables declaration//GEN-END:variables
}
